msf.cpp: ..\msf\msf.cpp
    copy /v ..\msf\msf.cpp .
	
mapfile.cpp: ..\msf\mapfile.cpp
    copy /v ..\msf\mapfile.cpp .

istream.h: ..\msf\istream.h
    copy /v ..\msf\istream.h .

crc32.cpp: ..\ilstore\crc32.cpp
	copy /v ..\ilstore\crc32.cpp .